apiVersion: v1
kind: ConfigMap
metadata:
  name: capris-config
data:
  NODE_ENV: "production"
  APP_TIMEZONE: "America/Costa_Rica"
  PORT: "4000"
  NEXT_PUBLIC_API_BASE_URL: "https://api.capris.example.com/api/v1"
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: ""
  CORS_ALLOWED_ORIGINS: "https://app.capris.example.com"
